// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iojnhzkatlyvbjlnblyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlvam5oemthdGx5dmJqbG5ibHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzOTUxNTksImV4cCI6MjA2NTk3MTE1OX0.xKOGN1-u-W3ZJuwroAhSe36OFSMjUDP8OIpbmcctGpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);